#!/usr/bin/env python3
"""Produce deterministic, user-gated action-card scaffolding from supplied evidence."""

from __future__ import annotations

import argparse
from pathlib import Path

from common import read_json, utc_now, write_json


CURRENT_AUTHORITIES = {"formal_current", "formal_verified_event"}


def list_from_payload(payload: object, key: str) -> list[dict[str, object]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        value = payload.get(key, [])
        return [item for item in value if isinstance(item, dict)] if isinstance(value, list) else []
    return []


def repository_name(unit: dict[str, object]) -> str | None:
    for key in ("repository", "repo", "repo_id"):
        value = unit.get(key)
        if isinstance(value, str) and value:
            return value.removeprefix("github:")
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", type=Path, required=True)
    parser.add_argument("--capture", type=Path, required=True)
    parser.add_argument("--purpose", type=Path)
    parser.add_argument("--content-units", type=Path)
    parser.add_argument("--context", type=Path)
    parser.add_argument("--repos", type=Path)
    parser.add_argument("--package-root", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    case = read_json(args.case)
    capture = read_json(args.capture)
    purpose = read_json(args.purpose) if args.purpose else {}
    units = list_from_payload(read_json(args.content_units), "content_units") if args.content_units else []
    snapshot = read_json(args.context) if args.context else {}
    contexts = list_from_payload(snapshot, "records")
    permitted_contexts = [
        item
        for item in contexts
        if item.get("authority_class") in CURRENT_AUTHORITIES and item.get("allowed_use") != "blocked"
    ]
    repos = list_from_payload(read_json(args.repos), "repositories") if args.repos else []
    repo_by_name = {
        str(item.get("repository") or item.get("repo_id", "")).removeprefix("github:"): item
        for item in repos
        if item.get("repository") or item.get("repo_id")
    }

    action_cards: list[dict[str, object]] = []
    for index, unit in enumerate(units, 1):
        name = repository_name(unit)
        matched_repo = repo_by_name.get(name) if name else None
        freshness = matched_repo.get("freshness_state", "unknown") if matched_repo else "unknown"
        recommendation = "research_refresh" if name and freshness in {"unknown", "aging", "stale"} else "catalog_only"
        action_cards.append(
            {
                "action_id": unit.get("unit_id") or f"action-{index}",
                "content_unit_id": unit.get("unit_id"),
                "recommendation": recommendation,
                "reason": "repository_metrics_or_current_decision_need_refresh" if recommendation == "research_refresh" else "candidate_requires_human_review",
                "same_as_existing": [matched_repo.get("repo_id")] if matched_repo else [],
                "new_vs_existing": "requires_semantic_review",
                "matched_context_ids": [item.get("record_id") or item.get("affair_id") for item in permitted_contexts],
                "matched_repo_ids": [matched_repo.get("repo_id")] if matched_repo else [],
                "evidence_refs": unit.get("evidence_refs", []),
                "freshness_state": freshness,
                "user_decision_required": True,
                "formal_write_authorized": False,
                "adoption_authorized": False,
            }
        )

    result = {
        "schema": "web-bookmark-intelligence/action-cards/v1",
        "created_at": utc_now(),
        "case_id": case.get("case_id") if isinstance(case, dict) else None,
        "capture_status": capture.get("final_status", capture.get("capture_status")) if isinstance(capture, dict) else None,
        "page_purpose": purpose.get("page_purpose_status", "requires_evidence_backed_semantic_interpretation") if isinstance(purpose, dict) else "requires_evidence_backed_semantic_interpretation",
        "page_purpose_request_used": bool(args.purpose),
        "context_status": "provided" if permitted_contexts else "context_insufficient",
        "context_records_used": [item.get("record_id") or item.get("affair_id") for item in permitted_contexts],
        "github_snapshots": repos,
        "action_cards": action_cards,
        "uncertainties": [
            "No semantic conclusion is generated by this deterministic scaffold.",
            "Repository stars/forks/watchers and updated_at remain source snapshots, not live values.",
        ],
        "formal_write_authorized": False,
        "install_authorized": False,
        "adoption_authorized": False,
    }
    write_json(args.out, result, args.package_root.resolve())
    print(f"action_cards={len(action_cards)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
